
import methods.Invoice;
import methods.Price;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bulouere
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoicePanel = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        stateInvoiceJTextField = new javax.swing.JTextField();
        cityInvoiceJTextField = new javax.swing.JTextField();
        nameInvoiceJTextField = new javax.swing.JTextField();
        jLabel127 = new javax.swing.JLabel();
        phoneNumberInvoiceJTextField = new javax.swing.JTextField();
        zipcodeInvoiceJTextField = new javax.swing.JTextField();
        jScrollPane39 = new javax.swing.JScrollPane();
        invoiceJTextArea = new javax.swing.JTextArea();
        companyNameInvoiceJTextField = new javax.swing.JTextField();
        streetAddressInvoiceJTextField = new javax.swing.JTextField();
        jLabel128 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        batchNumberInvoiceJComboBox = new javax.swing.JComboBox<>();
        quantityInvoiceJTextField = new javax.swing.JTextField();
        discountInvoiceJTextField = new javax.swing.JTextField();
        jLabel165 = new javax.swing.JLabel();
        unitPriceInvoiceJTextField = new javax.swing.JTextField();
        jLabel166 = new javax.swing.JLabel();
        totalPriceInvoiceJTextField = new javax.swing.JTextField();
        addToTableInvoiceJButton = new javax.swing.JButton();
        removeFromTableInvoiceJButton = new javax.swing.JButton();
        enterInvoiceJButton = new javax.swing.JButton();
        jLabel167 = new javax.swing.JLabel();
        jScrollPane40 = new javax.swing.JScrollPane();
        invoiceJTable = new javax.swing.JTable();
        printInvoiceJButton = new javax.swing.JButton();
        deleteInvoiceJButton = new javax.swing.JButton();
        clearAllInvoiceJButton = new javax.swing.JButton();
        jLabel132 = new javax.swing.JLabel();
        productNameInvoiceJComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoicePanel.setBackground(new java.awt.Color(204, 204, 204));
        invoicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("Invoice");
        invoicePanel.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1050, -1));

        jLabel106.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel106.setText("Name");
        invoicePanel.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel107.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel107.setText("Company Name");
        invoicePanel.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 30));

        jLabel123.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel123.setText("Street Address");
        invoicePanel.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel124.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel124.setText("City");
        invoicePanel.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        jLabel125.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel125.setText("State");
        invoicePanel.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 30));

        jLabel126.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel126.setText("Phone Number");
        invoicePanel.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        stateInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoicePanel.add(stateInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 100, 30));

        cityInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoicePanel.add(cityInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, 30));

        nameInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoicePanel.add(nameInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, 30));

        jLabel127.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel127.setText("Zipcode");
        invoicePanel.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, 30));

        phoneNumberInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoicePanel.add(phoneNumberInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 360, 30));

        zipcodeInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoicePanel.add(zipcodeInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, 30));

        invoiceJTextArea.setColumns(20);
        invoiceJTextArea.setRows(5);
        jScrollPane39.setViewportView(invoiceJTextArea);

        invoicePanel.add(jScrollPane39, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 380, 380));

        companyNameInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        companyNameInvoiceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameInvoiceJTextFieldActionPerformed(evt);
            }
        });
        invoicePanel.add(companyNameInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 150, 30));

        streetAddressInvoiceJTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoicePanel.add(streetAddressInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 370, 30));

        jLabel128.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel128.setText("Products");
        invoicePanel.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel130.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel130.setText("Batch Number");
        invoicePanel.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 30));

        jLabel163.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel163.setText("Quantity");
        invoicePanel.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 30));

        jLabel164.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel164.setText("Discount (%)");
        invoicePanel.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        batchNumberInvoiceJComboBox.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        batchNumberInvoiceJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNumberInvoiceJComboBoxActionPerformed(evt);
            }
        });
        invoicePanel.add(batchNumberInvoiceJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 150, 30));

        quantityInvoiceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityInvoiceJTextFieldActionPerformed(evt);
            }
        });
        invoicePanel.add(quantityInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 50, 30));

        discountInvoiceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountInvoiceJTextFieldActionPerformed(evt);
            }
        });
        invoicePanel.add(discountInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 50, 30));

        jLabel165.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel165.setText("Unit Price");
        invoicePanel.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, 30));

        unitPriceInvoiceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitPriceInvoiceJTextFieldActionPerformed(evt);
            }
        });
        invoicePanel.add(unitPriceInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 150, 30));

        jLabel166.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel166.setText("Total Price");
        invoicePanel.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, 30));

        totalPriceInvoiceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceInvoiceJTextFieldActionPerformed(evt);
            }
        });
        invoicePanel.add(totalPriceInvoiceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 150, 30));

        addToTableInvoiceJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        addToTableInvoiceJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmgtpackage/icons/cart-add-icon.png"))); // NOI18N
        addToTableInvoiceJButton.setText("Add to Table");
        addToTableInvoiceJButton.setToolTipText("Remove from Cart");
        addToTableInvoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToTableInvoiceJButtonActionPerformed(evt);
            }
        });
        invoicePanel.add(addToTableInvoiceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 40));

        removeFromTableInvoiceJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        removeFromTableInvoiceJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmgtpackage/icons/arrow-return-up-left-icon.png"))); // NOI18N
        removeFromTableInvoiceJButton.setText("Remove ");
        removeFromTableInvoiceJButton.setToolTipText("Remove from Cart");
        removeFromTableInvoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromTableInvoiceJButtonActionPerformed(evt);
            }
        });
        invoicePanel.add(removeFromTableInvoiceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, 40));

        enterInvoiceJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        enterInvoiceJButton.setText("Enter");
        enterInvoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterInvoiceJButtonActionPerformed(evt);
            }
        });
        invoicePanel.add(enterInvoiceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, 40));

        jLabel167.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel167.setText("Billing Information");
        invoicePanel.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        invoiceJTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        invoiceJTable.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        invoiceJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Price (NGN)", "Total", "Discount (%)", "Total after Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invoiceJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane40.setViewportView(invoiceJTable);

        invoicePanel.add(jScrollPane40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 520, 100));

        printInvoiceJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        printInvoiceJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmgtpackage/icons/print2-icon.png"))); // NOI18N
        printInvoiceJButton.setText("Print");
        printInvoiceJButton.setToolTipText("Print");
        printInvoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printInvoiceJButtonActionPerformed(evt);
            }
        });
        invoicePanel.add(printInvoiceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 100, 40));

        deleteInvoiceJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        deleteInvoiceJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmgtpackage/icons/delete-trash-empty-icon.png"))); // NOI18N
        deleteInvoiceJButton.setText("Delete");
        deleteInvoiceJButton.setToolTipText("See Product Catalogue");
        deleteInvoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvoiceJButtonActionPerformed(evt);
            }
        });
        invoicePanel.add(deleteInvoiceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, -1, 40));

        clearAllInvoiceJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        clearAllInvoiceJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmgtpackage/icons/small Clear-icon.png"))); // NOI18N
        clearAllInvoiceJButton.setText("Clear All");
        clearAllInvoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllInvoiceJButtonActionPerformed(evt);
            }
        });
        invoicePanel.add(clearAllInvoiceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, 40));

        jLabel132.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel132.setText("Product Name");
        invoicePanel.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        productNameInvoiceJComboBox.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        productNameInvoiceJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product" }));
        productNameInvoiceJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameInvoiceJComboBoxActionPerformed(evt);
            }
        });
        invoicePanel.add(productNameInvoiceJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companyNameInvoiceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameInvoiceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameInvoiceJTextFieldActionPerformed

    private void batchNumberInvoiceJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNumberInvoiceJComboBoxActionPerformed
        String batchNumberInvoice = (String) batchNumberInvoiceJComboBox.getSelectedItem();
        Price myPrice = new Price();
        myPrice.showPriceInvoice(batchNumberInvoice, unitPriceInvoiceJTextField);
    }//GEN-LAST:event_batchNumberInvoiceJComboBoxActionPerformed

    private void quantityInvoiceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityInvoiceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityInvoiceJTextFieldActionPerformed

    private void discountInvoiceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountInvoiceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountInvoiceJTextFieldActionPerformed

    private void unitPriceInvoiceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitPriceInvoiceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitPriceInvoiceJTextFieldActionPerformed

    private void totalPriceInvoiceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceInvoiceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceInvoiceJTextFieldActionPerformed

    private void addToTableInvoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToTableInvoiceJButtonActionPerformed
        Invoice myInvoice = new Invoice();
        myInvoice.addProductsToInvoiceTable(batchNumberInvoiceJComboBox, quantityInvoiceJTextField,
            unitPriceInvoiceJTextField, discountInvoiceJTextField, invoiceJTable);
    }//GEN-LAST:event_addToTableInvoiceJButtonActionPerformed

    private void removeFromTableInvoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromTableInvoiceJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeFromTableInvoiceJButtonActionPerformed

    private void enterInvoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterInvoiceJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterInvoiceJButtonActionPerformed

    private void printInvoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printInvoiceJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printInvoiceJButtonActionPerformed

    private void deleteInvoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInvoiceJButtonActionPerformed

    private void clearAllInvoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllInvoiceJButtonActionPerformed
        Invoice myInvoice = new Invoice();
        myInvoice.clearAll(nameInvoiceJTextField, companyNameInvoiceJTextField, streetAddressInvoiceJTextField,
            cityInvoiceJTextField, stateInvoiceJTextField, zipcodeInvoiceJTextField,
            phoneNumberInvoiceJTextField, batchNumberInvoiceJComboBox, unitPriceInvoiceJTextField,
            quantityInvoiceJTextField, discountInvoiceJTextField, totalPriceInvoiceJTextField);
    }//GEN-LAST:event_clearAllInvoiceJButtonActionPerformed

    private void productNameInvoiceJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameInvoiceJComboBoxActionPerformed
        Invoice myInvoice = new Invoice();
        myInvoice.linkProductAndBatchNumberCombos(productNameInvoiceJComboBox, batchNumberInvoiceJComboBox);
    }//GEN-LAST:event_productNameInvoiceJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToTableInvoiceJButton;
    private javax.swing.JComboBox<String> batchNumberInvoiceJComboBox;
    private javax.swing.JTextField cityInvoiceJTextField;
    private javax.swing.JButton clearAllInvoiceJButton;
    private javax.swing.JTextField companyNameInvoiceJTextField;
    private javax.swing.JButton deleteInvoiceJButton;
    private javax.swing.JTextField discountInvoiceJTextField;
    private javax.swing.JButton enterInvoiceJButton;
    private javax.swing.JTable invoiceJTable;
    private javax.swing.JTextArea invoiceJTextArea;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JTextField nameInvoiceJTextField;
    private javax.swing.JTextField phoneNumberInvoiceJTextField;
    private javax.swing.JButton printInvoiceJButton;
    private javax.swing.JComboBox<String> productNameInvoiceJComboBox;
    private javax.swing.JTextField quantityInvoiceJTextField;
    private javax.swing.JButton removeFromTableInvoiceJButton;
    private javax.swing.JTextField stateInvoiceJTextField;
    private javax.swing.JTextField streetAddressInvoiceJTextField;
    private javax.swing.JTextField totalPriceInvoiceJTextField;
    private javax.swing.JTextField unitPriceInvoiceJTextField;
    private javax.swing.JTextField zipcodeInvoiceJTextField;
    // End of variables declaration//GEN-END:variables
}
